#!/usr/bin/env bash
set -euo pipefail
# Generated by /cleanup — review every rm command before running.
# Run from vault root: bash queries/_cleanup.sh

# /lint run: 2026-06-02
# No pages proposed for deletion.
#
# All lint failures were structural (missing fields, missing backlinks,
# broken wikilinks, missing pages) — addressed through edits and new page
# creation, not deletions. No stubs, duplicates, or superseded drafts found.
#
# Agent-fixable lint failures (F1, F2, F5, F6) were applied directly
# in the same session as /cleanup. See wiki/PROJECT_STATUS.md for details.
#
# Manual action still required:
#   - Populate references.bib with 24 bib entries (references.bib is write-locked)
#   - Re-export or obtain Bécirović et al. (2025) PDF to resolve encoding error
